### PR TITLE
Moved frontend to main repo

### PR DESCRIPTION
**Pull request by shikhar-irez**
Part of #28

### CODE REVIEW

**Comment by rajivharlalka** [comment]
How about removing the submodule link and also moving data generation scripts in another directory to make the code clean?

Can additionally update the readme with the installation procedure for now and more things can follow later

**Comment by rajivharlalka** [comment]
That should be good.

**Comment by shikhar-irez** [comment]
Please review.

**Comment by rajivharlalka** [comment]
What do you think about moving all scripts into a different directory than the home, Would make things less cluttered

**Comment by shikhar-irez** [comment]
This is what I am thinking:
- [ ] Move frontend to main repo
- [ ] Rewrite first year scraper
- [ ] Make the directory structure cleaner
- [ ] Rewrite README in the same format as gyft.

**Comment by rajivharlalka** [comment]
Sounds good. Can add this as an issue and make changes in different PR's that can help in reviewing and faster merging. Ig 1,3,5  are solved in this PR itself.

**Comment by rajivharlalka** [comment]
Cool that works too.

**Comment by rajivharlalka** [comment]
May close this PR if you wish

**Comment by chirag-ghosh** [comment]
Let's just handle the first task in this PR.

**Comment by shikhar-irez** [comment]
Moving the frontend is done and also edited the README a bit. Merge this?
Then I will open PRs for other tasks.

**Comment by rajivharlalka** [comment]
Can be merged, but this is a good case where you can try git's cherry-pick. 
Try cherry-picking the commit for README changes to another branch,make another PR remove it from this. :)

**Review by chirag-ghosh — APPROVED** [review]

**Pull request merged**
