### PR TITLE
Move some of the data in code to json files

### LINKED ISSUE #2: Separation between data and code
While reading through the codebase, I found a couple of instances where we have hardcoded data:
- `departments` in `main.go`
- `rooms` in `rooms.go`

We can migrate these to their respective JSON files and read the data into the program whenever necessary. This will also help us abstract lots of details into useful and extensible data structures.

### PR DESCRIPTION
**Pull request by icyflame**
Fixes #2

### CODE REVIEW

**Comment by thealphadollar** [comment]
LGTM!

**Comment by icyflame** [comment]
@thealphadollar I hope you tested this out with a valid JSESSIONID? I am unable to get one because my ERP account doesn't work anymore! (The changes are fairly small, but still, it's good to test it. I will text you on Slack.)

**Comment by themousepotato** [comment]
Got an error @icyflame. Have a look.

```
2018/09/21 18:11:13 Request completed. Returning response now. Response length: 8756
2018/09/21 18:11:13 Found 0 subjects in department RX
2018/09/21 18:11:13 0 SUBJECTS FOUND.
HTML OUTPUT: <!DOCTYPE html><html><head><title>Apache Tomcat/8.0.51 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 500 - org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select a.subno from  ((select distinct subno from erp_acad_assignment_dtl where delete_flag='N'  and confirmation_flag='Y' and from_dept_code in () and session='2018-2019' and sem_no='AUTUMN' order by subno)  union  (select distinct subno  from timetable.time_table_dept where deptcode   in ()   and delete_flag='N' and subno not in ('B','HSS','Mgmnt/IT','IT','IEM') and substring(subno,1,2) in(select acad_code from admin_acad_dpcode where adm_code='RX') and session='2018-2019' and semester='AUTUMN'  order by subno  ) union  (select distinct subno   from timetable.time_table_first_year    where delete_flag='N' and session='2018-2019' and semester='AUTUMN'  and substring(subno,1,2) in (select acad_code from admin_acad_dpcode where adm_code='RX'  )))a order by a.subno]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near &quot;)&quot;</h1><div class="line"></div><p><b>type</b> Exception report</p><p><b>message</b> <u>org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select a.subno from  ((select distinct subno from erp_acad_assignment_dtl where delete_flag='N'  and confirmation_flag='Y' and from_dept_code in () and session='2018-2019' and sem_no='AUTUMN' order by subno)  union  (select distinct subno  from timetable.time_table_dept where deptcode   in ()   and delete_flag='N' and subno not in ('B','HSS','Mgmnt/IT','IT','IEM') and substring(subno,1,2) in(select acad_code from admin_acad_dpcode where adm_code='RX') and session='2018-2019' and semester='AUTUMN'  order by subno  ) union  (select distinct subno   from timetable.time_table_first_year    where delete_flag='N' and session='2018-2019' and semester='AUTUMN'  and substring(subno,1,2) in (select acad_code from admin_acad_dpcode where adm_code='RX'  )))a order by a.subno]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near &quot;)&quot;</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b></p><pre>org.apache.jasper.JasperException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select a.subno from  ((select distinct subno from erp_acad_assignment_dtl where delete_flag='N'  and confirmation_flag='Y' and from_dept_code in () and session='2018-2019' and sem_no='AUTUMN' order by subno)  union  (select distinct subno  from timetable.time_table_dept where deptcode   in ()   and delete_flag='N' and subno not in ('B','HSS','Mgmnt/IT','IT','IEM') and substring(subno,1,2) in(select acad_code from admin_acad_dpcode where adm_code='RX') and session='2018-2019' and semester='AUTUMN'  order by subno  ) union  (select distinct subno   from timetable.time_table_first_year    where delete_flag='N' and session='2018-2019' and semester='AUTUMN'  and substring(subno,1,2) in (select acad_code from admin_acad_dpcode where adm_code='RX'  )))a order by a.subno]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near &quot;)&quot;
  Position: 147
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:560)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.iitkgp.sso.ssoagent.client.SSOClientAgent.doFilter(SSOClientAgent.java:96)
</pre><p><b>root cause</b></p><pre>org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select a.subno from  ((select distinct subno from erp_acad_assignment_dtl where delete_flag='N'  and confirmation_flag='Y' and from_dept_code in () and session='2018-2019' and sem_no='AUTUMN' order by subno)  union  (select distinct subno  from timetable.time_table_dept where deptcode   in ()   and delete_flag='N' and subno not in ('B','HSS','Mgmnt/IT','IT','IEM') and substring(subno,1,2) in(select acad_code from admin_acad_dpcode where adm_code='RX') and session='2018-2019' and semester='AUTUMN'  order by subno  ) union  (select distinct subno   from timetable.time_table_first_year    where delete_flag='N' and session='2018-2019' and semester='AUTUMN'  and substring(subno,1,2) in (select acad_code from admin_acad_dpcode where adm_code='RX'  )))a order by a.subno]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near &quot;)&quot;
  Position: 147
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.translate(SQLStateSQLExceptionTranslator.java:108)
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:322)
	org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:382)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:433)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:441)
	org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:472)
	org.apache.jsp.timetable_005ftrack_jsp._jspService(timetable_005ftrack_jsp.java:482)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.iitkgp.sso.ssoagent.client.SSOClientAgent.doFilter(SSOClientAgent.java:96)
</pre><p><b>root cause</b></p><pre>org.postgresql.util.PSQLException: ERROR: syntax error at or near &quot;)&quot;
  Position: 147
	org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
	org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
	org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
	org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
	org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
	org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:206)
	org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:206)
	org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:418)
	org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:433)
	org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:441)
	org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:472)
	org.apache.jsp.timetable_005ftrack_jsp._jspService(timetable_005ftrack_jsp.java:482)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.iitkgp.sso.ssoagent.client.SSOClientAgent.doFilter(SSOClientAgent.java:96)
</pre><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/8.0.51 logs.</u></p><hr class="line"><h3>Apache Tomcat/8.0.51</h3></body></html>
```

**Comment by icyflame** [comment]
@themousepotato This is an error thrown by the ERP's Server (Apache Tomcat). This is not an error in the Go code.

**Comment by themousepotato** [comment]
Cool @icyflame.

**Comment by thealphadollar** [comment]
@icyflame I just tested it; works fine :)

**Comment by icyflame** [comment]
@thealphadollar that sounds great! :slightly_smiling_face: Thanks for testing it, it was totally my bad for opening a patch without testing it. :)

**Pull request merged**
