### PR TITLE
new logo files added

### PR DESCRIPTION
**Pull request by Dattax**
I have created 3 logo files for you to add to the header area - let me know if you need any additional help on these.

### CODE REVIEW

**Comment by thealphadollar** [comment]
@Dattax Thanks a lot for the PR; I'm very impressed by the efforts you've put.

However, unfortunately, we are looking for something closer to an icon, as we want a minimalistic logo to represent on the website.

It should be square and appropriate as an icon. I do appreciate your efforts and will include this in the README.md

**Comment by Dattax** [comment]
Oh - why didn't you say so?

Show me some examples you like and I'll make a great one!

**Comment by Dattax** [comment]
Got it! Show me some examples and I will make one :)

**Comment by thealphadollar** [comment]
Sure. I apologize for not being specific.

Here are some icon examples I found on the internet :smiley: 

image

**Comment by Dattax** [comment]
You can use these for now I guess

**Comment by Dattax** [comment]
logo1-black
logo1-white
logo2-black
logo2-white

**Comment by thealphadollar** [comment]
I would like to have blue on a transparent background as the color scheme.

**Comment by Dattax** [comment]
design1
design2
design3
design4
design5
design6
design7
design8

**Comment by thealphadollar** [comment]
@Dattax Thanks a lot, very impressive graphics :)

I really like the below one and would love if you can create favicons out of the image using [realfavicongenerator](https://realfavicongenerator.net/) and place it at appropriate places in the application 🛩 

image

**Comment by Dattax** [comment]
The rest is on your team now :) Thanks!

**Comment by thealphadollar** [comment]
Cool. Your help is highly appreciated 😄

**Comment by thealphadollar** [comment]
@Hahkarthick Please find the logo in the comment above.

**Pull request closed without merging**
